apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: myacr.azurecr.io/myapp:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "900m"
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: azure-disk-storage
  volumes:
  - name: azure-disk-storage
    persistentVolumeClaim:
      claimName: azure-managed-disk-pvc

